name: talker_dio_logger_plus
description: Advanced and feature-rich Dio HTTP client logger with cURL export, JSON viewer, detail views, image support, and more
version: 1.0.1

homepage: https://github.com/CompileConnected/talker_dio_logger_plus
repository: https://github.com/CompileConnected/talker_dio_logger_plus
issue_tracker: https://github.com/CompileConnected/talker_dio_logger_plus/issues

topics:
  - dio
  - talker
  - log
  - logger

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  talker: ">=4.5.0"
  talker_flutter: ">=4.5.0"
  path_provider: ^2.1.0
  share_plus: ">=10.1.4"
  archive: ^4.0.2
  http_parser: ^4.0.0
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

